# Generated by Django 4.2 on 2024-10-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=20)),
                ('correo', models.EmailField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
