# Generated by Django 4.2 on 2024-10-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crude', '0008_cliente_tel_alter_cliente_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tel',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.TextField(max_length=20),
        ),
    ]
