# Generated by Django 4.2 on 2024-10-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crude', '0009_remove_cliente_tel_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
